from pathlib import Path
import json,hashlib,math
import pandas as pd
P=Path(__file__).resolve().parent
pub={x['ticker']:x for x in json.loads((P/'publication/quotes-and-plan.json').read_text())};rows={x['ticker']:x for x in json.loads((P/'all-factors.json').read_text())};rank=json.loads((P/'low-gain-ranked.json').read_text());strict=json.loads((P/'strict-original/audit.json').read_text());credit=json.loads((P/'credit-context.json').read_text())
now=pd.Timestamp.now(tz='UTC').isoformat()
def save(name,x): (P/name).write_text(json.dumps(x,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
facts=[dict(ticker='IREN',source='https://irisenergy.gcs-web.com/news-releases/news-release-details/iren-reports-fy26-results',published='2026-08-27',quarter_revenue_musd=137.2,year_revenue_musd=707.0,prior_year_revenue_musd=501.0,annual_yoy=707/501-1,ai_revenue_musd=70.5,prior_quarter_ai_musd=33.6,operating_arr_busd=1,contracted_arr_busd=4,arr_is_not_gaap=True,interpretation='AI ramp operating narrative; not current newcatalyst or tomorrowpromise'),dict(ticker='IREN',source='https://irisenergy.gcs-web.com/news-releases/news-release-details/iren-reports-full-year-fy25-results',published='2025-08-28',prior_year_quarter_revenue_musd=187.3,latest_quarter_yoy=137.2/187.3-1,original_revenue_gate=False),dict(ticker='APLD',source='https://ir.applieddigital.com/news-events/press-releases/detail/159/applied-digital-reports-fiscal-fourth-quarter-and-full-year',published='2026-07-27',quarter_revenue_musd=258.748,prior_quarter_same_year_musd=51.076,quarter_yoy=258748/51076-1,tenant_fitout_musd=152.4,base_rent_musd=44.1,net_loss_common_musd=110.6,original_revenue_gate=True,not_profit_growth=True),dict(ticker='APLD',source='https://ir.applieddigital.com/news-events',published='2026-09-28T16:05:00-04:00',earnings='2026-10-07T17:00:00-04:00',not_tomorrow_catalyst=True),dict(ticker='CBRS',source='https://investors.cerebras.ai/news-releases/news-release-details/cerebras-systems-fast-inference-cloud-business-nearly-quadruples',published='2026-08-12',gaap_rev_yoy=180110/103322-1,core_non_gaap_rev_yoy=1.03,rpo_busd=25.4,raised_core_full_year_outlook=True,price_confirmation_today=False),dict(ticker='NBIS',source='https://nebius.com/newsroom/nebius-acquires-inferize-to-strengthen-nebius-token-factorys-production-inference-stack',published='2026-10-01',claim='Inferize acquisition to strengthen production inference stack',verified_method='official searchindex; direct open inaccessible',new_today=True,financial_impact_not_quantified=True),dict(ticker='CRWV',source='https://investors.coreweave.com/news/news-details/2026/CoreWeave-Prices-Upsized-3-7-Billion-Convertible-Senior-Notes-Offering/default.aspx',published='2026-09-18',convertible_busd=3.7,not_current_Tminus3_veto=True),dict(source='https://www.bls.gov/schedule/2026/10_sched.htm',employment_report='2026-10-02T08:30:00-04:00')]
save('verified-evidence.json',dict(verified_at=now,facts=facts,event_coverage_complete=False))
decision=dict(decision_at=now,scope='152 attentionstocks;lowgain<=3% vsSep30close;not wholemarket',relative_first='APLD',price_shape_first='IREN',formal_babybus_entries=0,formal_babybus_observations=0,manual_identity_confirmed=['IREN','APLD','CBRS'],original_identity_false_is_stale_metadata=True,absolute_buy_certification=False,strict_probability_nextday5=None,original_horizon_days=3,original_targets=[.08,.12],current_one_day_observation_untested=True,model_direction_weight=0,score_not_issued='unified12factor coverage insufficient;originalrank65pct doesnotpass80pct',financial_judgment='IRENquartertotalrevenue-26.75pctfails50pctgate;APLDpassesrevenuegatebutweeklyvol8.16pctfails12pctplusnovolumegreen',adapted_watch_conditions=dict(ticker='APLD',reclaim_open=24.44,hold_updated_vwap=True,two_complete5m_above_vwap=True,sameclock_rvol_min=1.5,not_formal_strategy=True,not_probability_confirmation=True,entry_cap_requires_recompute_after_trigger=True,illustrative_entry=24.5,illustrative_stop=24.5*.97,illustrative_gross5=24.5*1.05,illustrative_net5_costproxy=24.5*1.052,deadline='2026-10-02T15:55:00-04:00'),latest_quotes=pub,independent_risk_alerts=['credit20returnnegative andcompletedweeklybreak','Oct2NFP0830 overnightgap beyondstop','noPITfullfinancial,eventcoverage/options/flows','APLDweeklyvolbeloworiginalminimum andlowmarginfitoutgrowth','IRENGAAPrevenuefailsstory','CBRSdownvolumeunderVWAP','CRWVprovisional3upcloses,awaitcompletedclose','largeone_dayATRdoesnotimplypositive5pctprobability'],account_nav_options_unknown=True,user_execution='unknown',outcomes='pending',orders_sent=False)
save('decision.json',decision)
lines=['2026-10-01 Babybus低涨幅次日机会｜行情约15:31 EDT','结论：综合观察首选APLD；价格洗盘形态最接近IREN。没有可称“明天大概率涨5%”的严格Babybus候选。现在不是完整策略买入信号，不据此建议清空AVGO换入。','策略来源：本地Babybus风格重建及BB_WASHOUT_BOUNCE_V1，不代表作者官方原版或已验证胜率。原洗盘策略最多3日、-5%止损、+8%/+12%退出；原周线信用版不是隔日暴涨策略。','样本：152只既有关注池，全部价格解析成功。日线截至9月30日；完整周线截至9月25日；盘中价格与70个完整5分钟因子截止15:20，公布快照72个完整5分钟截至15:30。前20个同钟完整交易日作为量比基准；所有缺失单列，不补零。','原14只股票日终策略重放：正式观察0、买入前候选0；65%排名覆盖未过80%。旧证券身份标记不代表今日无法确认；今日IR已确认IREN/APLD身份。事件覆盖/完整财务快照缺失独立于实质条件不达标。']
for s in ['APLD','IREN','CBRS','NBIS','CRWV','VRT']:
 q=pub[s];r=rows[s];rv='缺失' if q['rvol_sameclock'] is None else f"{q['rvol_sameclock']:.2f}"
 lines.append(f"{s}：{q['price']:.3f}美元，今日{q['change_pct']:+.2f}%，行情{q['quote_at']}；同钟量比{rv}，日内VWAP{q['vwap']:.3f}；高点回撤{r['dd_high']:.1%}（15:25快照），10日回撤{r['dd10']:.1%}，12周波动{r['weekly_vol']:.2%}；ATR14 {r['atr14']:.3f}。")
lines+=['APLD：高点回撤约52%、10日回撤约17%、距20日低点约3%，符合洗盘/近支撑结构；12周波动8.16%低于12%，量比约1.09且低于开盘价，缺少放量阳线。最新季总营收同比+407%，其中租户装修152.4m，对应基租44.1m；不可将装修收入增长等同持续利润。财报在10月7日17:00，不是明天。','IREN：高点回撤约48%、10日回撤约19%，90日年化波动105%、12周波动12.23%；昨日日终RSI2 2.41超卖，但量比1.02并非放量。AI收入70.5m相比前季33.6m增长；总收入137.2m相比去年同期187.3m同比-26.75%，未达50%总收入门槛。FY26总收入+41.12%也未达50%；合同ARR不是确认收入。','CBRS：GAAP营收同比+74%、RPO25.4bn，但今日-4.58%，量比1.94而价格169.52低于VWAP174.59，接近当日低点；是下跌放量，不登记吸筹。12周波动11.41%也不足12%。上市未满252交易日，高点回撤是上市以来可用历史高点。','NBIS：今日有Inferize收购公告，但回撤仅22%，未过35%门槛，同钟量比0.84；这份新公告没有量化明日盈利重估，不能只凭未涨推导即将补涨。CRWV同钟量比0.67；现价意味着若收盘保持，将是3个连续上涨收盘，触及原策略追涨限制，当前不能把未完成日终当最终结果。9月18日融资不是今日T-3事件否决。','信用背景：JNK截至9月30日复权20日总回报-2.58%；完整9月25日周线低于此前8周最低收盘的99.5%门槛。月末3/10月均线没有熊叉；OAS20变化及3日信用确认未完成，不能声称信用ON。该周线规则与3日洗盘模型分开，不混改概率。','观察触发（另拟的一日反弹条件，未经策略胜率验证）：APLD重回24.44开盘价，保持动态VWAP上方且连续2个完整5分钟收盘站上，同钟量比至少1.5；当前未满足。触发时需重新核对报价和入场上限。即使触发，原12周波动等条件仍不通过，不能升级成正式Babybus信号。','若仅作计划示例：实际成交24.50美元时，-3%失效参考23.77，毛收益+5%为25.73，假定来回成本0.2%后净5%需约25.77；10月2日15:55结束这一日计划。百分比随实际成交重算，隔夜跳空会穿越止损。这不是委托或确定会达标的预测。','最大置信结论：能确认的是已通过/未通过条件；没有经样本外校准的次日5%概率或置信区间。此前7因子失败模型权重0，不冒充Babybus验证。个人账户净值/期权/风险预算未知，不给最优全账户股数。','独立风险：明日10月2日8:30 EDT非农就业；信用未确认ON；装修收入与持续租金不同；财务/事件/期权/真实资金流证据不完整。低换手或缩量本身不能证明机构吸筹。','半导体背景：CBRS是本地根据主营业务归类为AI芯片/算力基础设施，网站公司组未知；使用caller-supplied semiconductor行业代理。网站情绪日期10月1日02:02:10 UTC、周期02:03:23，抓取14:37:50.780674 UTC；AI77/Extreme greed、广义70/Greed、周期83/Peak conditions。存储9月29日02:35:41与政策9月7日模块超过48小时，排除今日新增证据；行业背景不增加上涨概率。','来源：']
lines += [x['source'] for x in facts]
lines+=['行情来源：Yahoo chart v8；所有原始字节及抓取时间、SHA256留档；不是经纪商可成交买卖价。','实际买入未知；次日结果未成熟；不下单。']
(P/'筛选结论与观察条件.txt').write_text('\n'.join(lines)+'\n')
# Proportionate numerical checks: original parameters, rawintegrity, dateboundary, gates, intervalcompleteness.
checks=[]
for orig,copy in [('config/bb_washout_bounce.yaml','original-bb-config.yaml'),('config/bb_universe.json','original-bb-universe.json')]:
 assert Path(orig).read_bytes()==(P/copy).read_bytes();checks.append('original config/universe unchanged: '+orig)
for m in json.loads((P/'strict-raw/manifest.json').read_text()):assert hashlib.sha256((P/'strict-raw'/m['file']).read_bytes()).hexdigest()==m['sha256']
checks.append('161 reused/fresh daily raw snapshots SHA256verified')
for m in json.loads((P/'publication/manifest.json').read_text()):assert hashlib.sha256((P/'publication/raw'/f"{m['symbol']}-live.json").read_bytes()).hexdigest()==m['sha256']
checks.append('6 publication snapshots SHA256verified')
assert len(rows)==152 and not any('error'in r for r in rows.values());assert len(strict)==14 and sum(x['entry'] for x in strict)==0
assert credit['weekly_end'].startswith('2026-09-25') and credit['completed_session'].startswith('2026-09-30');checks.append('incomplete today/week excluded')
assert all(q['complete5m_count']==q['expected5m_count']==72 for q in pub.values());assert all(q['rvol_reference_count']>=20 and q['rvol_sameclock'] is not None for q in pub.values());checks.append('72 complete5m bars,20prior completeclock references')
assert abs(137.2/187.3-1-(-.26748531767218375))<1e-12;assert rows['APLD']['weekly_vol']<.12 and pub['APLD']['rvol_sameclock']<1.5;assert pub['CBRS']['price']<pub['CBRS']['vwap'];checks.append('independent revenue/volumegate/pricevsVWAPsanity')
assert math.isclose(24.5*1.05,25.725) and math.isclose(24.5*.97,23.765);checks.append('actual entry example target/stop numerical identity')
save('verification.json',dict(at=now,checks=checks,functional_success=True,investment_probability_validated=False))
reg=Path('量化参考/优先策略/案例登记.json');registry=json.loads(reg.read_text());runid='2026-10-01-Babybus低涨幅次日机会';assert not any(x.get('id')==runid for x in registry.get('screening_runs',[]))
# Preserve actual top-level run field used by existing registry.
runkeys=[k for k,v in registry.items() if isinstance(v,list) and v and isinstance(v[-1],dict) and 'id' in v[-1] and k!='cases'];rk=runkeys[-1] if runkeys else 'screening_runs'
registry.setdefault(rk,[]).append(dict(id=runid,decision_at=now,relative_first='APLD',price_shape_first='IREN',absolute_buy_certification=False,probability_tomorrow5=None,formal_babybus_entries=0,report=str(P/'筛选结论与观察条件.txt'),decision=str(P/'decision.json'),all_candidate_file=str(P/'all-factors.json'),failed_candidate_file=str(P/'strict-original/rejects.csv'),known_evidence_file=str(P/'verified-evidence.json'),publication_snapshot=str(P/'publication/quotes-and-plan.json'),retained_failed_candidates=['IREN','CBRS','NBIS','CRWV','ALAB','VRT'],actual_bought_shares=None,actual_execution_price=None,user_execution='unknown',future_outcome='pending',not_a_trade=True))
registry['saved_at']=now;reg.write_text(json.dumps(registry,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'relative_first':decision['relative_first'],'strict_signals':0,'verification_checks':len(checks),'registry_run_key':rk,'low_gain_liquid_count':len(rank)},ensure_ascii=False))
