"""Byte-for-byte replay locks for the ten existing raw golden sessions.

The checked-in hashes are reviewed artifacts, never regenerated by these tests.
The hand-written scenario projections are asserted directly. Their only
authorized edit is the PAUSE action spelling, recorded in the fixture itself.
"""
from copy import deepcopy
from hashlib import sha256
import json
from pathlib import Path

import pytest

from macro_engine import decide
from macro_engine.surge import estimate
from test_macro_engine_golden import assert_projection


FIXTURES = Path(__file__).parent / "fixtures" / "golden"
CASES = json.loads((FIXTURES / "cases.json").read_text())["cases"]
FUTURE_DAY = "2026-10-15"
FUTURE_CLOSE = "2026-10-15T20:00:00+00:00"
EXECUTION_FIELDS = ("action", "size_unit", "constraints")


def load_input(case):
    """Load the same persisted raw evidence without replacing the macro adapter."""
    facts = json.loads((FIXTURES / case["raw_facts"]).read_text())
    for series, omissions in case["omit_publications"].items():
        facts["publications"][series] = [
            row for row in facts["publications"][series]
            if row["date"] not in omissions
        ]
    for symbol in case["omit_consensus"]:
        facts["consensus"].pop(symbol, None)
    return deepcopy(case["book"]), facts, deepcopy(case["policy_statements"])


def canonical_json(value):
    # Match Decision.to_json(), including its default separators and UTF-8 text.
    return json.dumps(value, sort_keys=True, ensure_ascii=False, allow_nan=False)


def digest(serialized):
    return sha256(serialized.encode("utf-8")).hexdigest()


def execution_json(decision):
    output = decision.to_dict()
    return canonical_json({field: output[field] for field in EXECUTION_FIELDS})


def hash_document():
    document = json.loads((FIXTURES / "decision_hashes.json").read_text())
    assert document["version"] == 1
    assert document["hash_algorithm"] == "sha256"
    assert document["update_reason"] == "closest only"
    assert document["baseline_stage"] == "after PAUSE action rename, before closest"
    assert [(row["id"], row["asof"]) for row in document["cases"]] == [
        (case["id"], case["asof"]) for case in CASES
    ]
    for row in document["cases"]:
        assert set(row) == {"id", "asof", "baseline_sha256", "sha256"}
        for key in ("baseline_sha256", "sha256"):
            assert len(row[key]) == 64
            assert set(row[key]) <= set("0123456789abcdef")
    return document


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["id"])
def test_golden_decision_json_sha256_is_locked(case):
    book, facts, statements = load_input(case)
    decision = decide(book, facts, statements, case["asof"])
    locked = next(row for row in hash_document()["cases"]
                  if row["id"] == case["id"])
    assert digest(decision.to_json()) == locked["sha256"], case["id"]

    # This one-time lock revision must be attributable only to trace.closest.
    # The PAUSE spelling change was already included in the captured baseline.
    baseline = decision.to_dict()
    assert "closest" in baseline["trace"]
    baseline["trace"].pop("closest")
    assert digest(canonical_json(baseline)) == locked["baseline_sha256"], case["id"]


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["id"])
def test_hand_written_projection_is_preserved(case):
    book, facts, statements = load_input(case)
    assert_projection(decide(book, facts, statements, case["asof"]).to_dict(),
                      case["expected_projection"])


def append_future_prices(facts, statements):
    for group in ("prices", "macro_prices"):
        for rows in facts[group].values():
            row = deepcopy(rows[-1])
            row.update(date=FUTURE_DAY, available_at=FUTURE_CLOSE,
                       adj_close=999999., adj_open=1.)
            if group == "macro_prices":
                row["close"] = 999999.
            rows.append(row)


def append_future_statement(facts, statements):
    statements.append({
        "date": FUTURE_DAY,
        "action": "CUT",
        "target_range": [0., .25],
        "source": "https://www.federalreserve.gov/synthetic/golden/lock-future.htm",
        "verified": True,
        "available_at": "2026-10-15T18:00:00+00:00",
    })


def append_future_consensus(facts, statements):
    facts["consensus"].setdefault("COREX", []).append({
        "date": FUTURE_DAY,
        "eps": -999999.,
        "fiscal_period": "FY2027",
        "is_consensus": True,
        "source": "synthetic://golden/lock-future-consensus",
        "verified": True,
        "available_at": FUTURE_CLOSE,
    })


@pytest.mark.parametrize("append", [append_future_prices, append_future_statement,
                                   append_future_consensus],
                         ids=["prices", "statement", "consensus"])
@pytest.mark.parametrize("case", CASES, ids=lambda case: case["id"])
def test_each_future_evidence_append_preserves_full_asof_json(case, append):
    book, facts, statements = load_input(case)
    before = decide(book, facts, statements, case["asof"]).to_json()
    assert FUTURE_DAY > case["asof"]
    append(facts, statements)
    after = decide(book, facts, statements, case["asof"]).to_json()
    assert after == before


@pytest.mark.parametrize("case", CASES, ids=lambda case: case["id"])
def test_surge_probability_changes_only_read_only_annotation(case):
    book, facts, statements = load_input(case)
    decision = decide(book, facts, statements, case["asof"])
    original_json = decision.to_json()
    original_execution = execution_json(decision)
    annotation = estimate("COREX", case["asof"], {
        "regime": decision.regime,
        "stress": decision.stress["state"],
        "dip_unit": decision.size_unit,
        "yield_stable": False,
        "at_252_high": False,
    })
    assert annotation["p"] is None and annotation["abstain"] is True
    assert annotation["reason"] == "no_pit_panel"
    annotated = []
    for probability in (.99, None):
        changed = deepcopy(annotation)
        changed["p"] = probability
        attached = decision.with_surge([changed])
        assert execution_json(attached) == original_execution
        output = attached.to_dict()
        assert output["surge"] == [changed]
        output["surge"] = []
        assert canonical_json(output) == original_json
        annotated.append(attached.to_json())
    assert annotated[0] != annotated[1]
    assert decision.to_json() == original_json
